<script setup>
import { computed, onMounted, ref } from 'vue'
import { api, apiError, responseData } from '../../api'
import AdminState from '../../admin/AdminState.vue'
const data=ref(null),loading=ref(false),error=ref(''),from=ref(''),to=ref('')
const money=value=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(value||0))
const maxRevenue=computed(()=>Math.max(1,...(data.value?.revenue_by_period??[]).map(item=>Number(item.revenue??item.value??0))))
async function load(){loading.value=true;error.value='';try{data.value=responseData(await api.get('/admin/analytics',{params:{from:from.value||undefined,to:to.value||undefined}}))}catch(err){error.value=apiError(err)}finally{loading.value=false}}
onMounted(load)
</script>
<template><section><header class="admin-page-head"><div><h1>Phân tích kinh doanh</h1><p>Doanh thu, công suất và nguồn đặt phòng theo thời gian</p></div></header><div class="admin-card" style="margin-bottom:18px"><div class="admin-toolbar"><label class="admin-field"><span>Từ ngày</span><input v-model="from" class="admin-input" type="date"/></label><label class="admin-field"><span>Đến ngày</span><input v-model="to" class="admin-input" type="date"/></label><button class="admin-button" @click="load">Áp dụng</button></div></div><AdminState :loading="loading" :error="error" :empty="!loading&&!error&&!data" @retry="load"/><template v-if="data&&!loading"><div class="admin-kpis"><article class="admin-card admin-kpi"><span class="admin-kpi-label">Tổng doanh thu</span><strong class="admin-kpi-value">{{money(data.total_revenue)}}</strong></article><article class="admin-card admin-kpi"><span class="admin-kpi-label">Số đặt phòng</span><strong class="admin-kpi-value">{{data.total_bookings??0}}</strong></article><article class="admin-card admin-kpi"><span class="admin-kpi-label">Giá trị trung bình</span><strong class="admin-kpi-value">{{money(data.average_booking_value)}}</strong></article><article class="admin-card admin-kpi"><span class="admin-kpi-label">Công suất</span><strong class="admin-kpi-value">{{data.occupancy_rate??0}}%</strong></article></div><div class="admin-dashboard-grid"><article class="admin-card"><header class="admin-panel-head"><h2>Doanh thu theo kỳ</h2></header><div class="admin-panel-body admin-bars"><div v-for="(item,index) in data.revenue_by_period??[]" :key="index" class="admin-bar-item"><div class="admin-bar" :style="{height:`${Number(item.revenue??item.value??0)/maxRevenue*100}%`}"></div><span>{{item.label??item.date}}</span></div></div></article><article class="admin-card"><header class="admin-panel-head"><h2>Nguồn đặt phòng</h2></header><div class="admin-panel-body"><div v-for="item in data.booking_sources??[]" :key="item.source" class="admin-progress-row"><div class="admin-progress-meta"><span>{{item.source}}</span><b>{{item.percent??item.value}}%</b></div><div class="admin-progress"><span :style="{width:`${item.percent??item.value}%`}"></span></div></div><p v-if="!data.booking_sources?.length">Chưa có dữ liệu nguồn đặt phòng.</p></div></article></div></template></section></template>
